import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import connect from "@/libs/mongodb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connect();
  return (
    <html lang="en">
      <body className="bg-white m-auto max-w-3xl">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
